Feature/issue 18
ayabe2000/nutrition_app pull request #19
Opened 2023-09-14 11:11 UTC by ayabe2000

機能を追加しました。
他のブランチでプッシュしてしまい、この機能を追加する変更点はありません。

2023-09-15 00:21 UTC, masatanish requested changes
グラフ機能の修正の差分はこのPRにはほとんど含まれなかったので、別途レビューしてIssueを起こそうと思います。

`.gitignore`の記載に問題がありそうなので修正してください。

2023-09-15 00:21 UTC, masatanish commented on .gitignore
> +requirements.txt
`new_venv`とはなんでしょうか？
READMEにはそのような記載はありません。
ローカルPC内での変更をgitignoreに含めるのはやめましょう。


requirements.txtを .gitignoreに追加するのは問題があります。
(ソースを参照する人がどのパッケージを使うのかが分からなくなります)

この修正が必要な理由がある場合にはそれを明示してください。
そうでない場合は削除してください

`nutirent_intake.png` が重複しているように見えます。
削除してください。

2023-09-15 00:31 UTC, masatanish commented
あと、以前もお伝えしましたがPRのタイトルは内容がわかるものにしてください。

2023-09-15 05:39 UTC, ayabe2000 commented on .gitignore
> +requirements.txt
nutirent_intake.pngの重複を消してstaticを.gitignoreに入れる認識でよろしいでしょうか。
それともstatic自体は.gitignore追加しない方が方がよろしいでしょうか。
new_venvはvenvが起動しなくなってしまったので切り替えました。.gitignoreから削除しました。

2023-09-19 00:22 UTC, ayabe2000 commented on .gitignore
> +requirements.txt
プルリクエストの整理をするために下記を削除しました。
誤って追加したものを削除するという認識でありましたが、問題ないでしょうか。
よろしくお願いいたします。
new_venv
nutirent_intake.png
requirements.txt

2023-09-19 00:32 UTC, masatanish commented
現在の修正内容でOKです。main ブランチにマージしてください。
mainブランチとコンフリクトを起こしていると表示が出ています。
git の merge と コンフリクトの解決について調べながら対応して、mainブランチへのマージをお願いします。

2023-09-19 02:12 UTC, merged