cssを適用させる
ayabe2000/nutrition_app pull request #32
Opened 2023-09-19 08:18 UTC by ayabe2000

cssを利用していなくページに色味がなかったので見やすくするため、Tailwindを利用して見た目を改善させました。

変更点は
templatesのlogin.html

link タグを使ってTailwind CSSのスタイルシートを含めてます。
body タグにTailwind CSSクラスを追加して背景色を設定し、コンテンツを垂直と水平の中央に配置してます。
フォームの周囲に背景色、パディング、丸みを帯びた角、影を追加するためのTailwind CSSクラスを追加してます。
フォームフィールドとボタンにTailwind CSSクラスを追加してスタイリングしてます。

dashboard.html

背景色とテキスト色を変更して視覚的なコントラストを向上させました。
コンテナとパディングを追加して、コンテンツをよりセンタリングしました。
フォームとエントリーのセクションに背景色、パディング、角丸を追加してカードスタイルのデザインを実装しました。
ボタンに色とホバーエフェクトを追加しました。
全体的なマージンとパディングを調整して、スペースを均等に分配しました。
リストのスタイルを改善しました。

edit_food.html

head セクションと link タグを追加してCSSスタイルシートをリンクさせました。
body タグにTailwind CSSクラスを追加し、背景色を設定し、コンテンツを垂直、水平の中央に配置しました。

ご確認お願いいたします。

2023-09-20 00:53 UTC, masatanish requested changes

2023-09-20 00:53 UTC, masatanish commented on templates/dashboard.html
> +    <link rel="stylesheet" href="/static/styles.css">
Tailwind公式のGetting Started(https://tailwindcss.com/docs/installation/play-cdn)では、 <script>でcdnのファイルを読み込むようになっていますが、そうなっていないのは何故でしょう？

また、こちらの書き方では static/styles.css を参照するようになっていますが、styles.cssがファイルとして追加されていません。
なので、他の人の環境ではcssが適用されないと思います。

で、cssは多分ファイルサイズが大きくなるので、何か特別な理由がない限りはCDNのスクリプトを参照したほうが良いと考えます。

2023-09-20 03:04 UTC, ayabe2000 commented on templates/dashboard.html
> +    <link rel="stylesheet" href="/static/styles.css">
Tailwind公式の参照して
CDN スクリプトを HTML に追加し、tailwind.configオブジェクトを編集して構成をカスタマイズしました。
(login.html,dashboard.html)
content-visibility: auto;というCSSプロパティを適用しました。
(dashboard.html,edit_food.html)
ファーストパーティのプラグインを適用しました。
(login.html)

変更の記載はないと思いますが、
static/styles.cssを削除し、src/input.cssを追加しました。

ご確認お願いいたします。

2023-09-24 23:35 UTC, masatanish commented
良いかと思います。 mainブランチとのコンフリクトを解消してマージしてください

2023-09-24 23:58 UTC, merged