エラー修正とユーザー識別
ayabe2000/nutrition_app pull request #45
Opened 2023-09-22 06:06 UTC by ayabe2000

generate_graph.pyでエラーが起こっていたので修正と、
１日の栄養摂取量と履歴がユーザーを切り替えても同じデータを表示してしまうという問題を解決する為に、ユーザーの識別を考慮するコードを追加しました。

変更点は
generate_graph.pyで
get_image_data関数内のencoded_image変数を定義
fetch_data関数でのuser_idを認識されるように{'user_id': user_id}に変更

views.py
get_nutrients_data_today、compute_nutrients、group_entries_by_date関数に指定されたユーザーの栄養データのみを取得できるように変更。
dashboard関数で
nutrients_data = compute_nutrients(all_entries, user_id)
entries = group_entries_by_date(all_entries, user_id)
に変更。(user_idという引数追加)

ご確認よろしくお願いいたします。

2023-09-24 23:56 UTC, masatanish reviewed
詳細な変更点の説明の前に不具合の原因と、修正方針の概要を記載してください。
レビューがしにくいので。

2023-09-24 23:56 UTC, masatanish commented on generate_graph.py
> +
`foods`の削除など不具合と関係ない変更が含まれているのでもとに戻してください。
不具合に関係ある変更のみをいれてください。
レビューする側として混乱します。

foodsを消したいのであれば、別のIssue, PRを作製してください

2023-09-25 02:41 UTC, ayabe2000 commented
エラー修正は
return encoded_imageの部分のencoded_imageが未定義であったことが原因であったので、定義するためにget_image_data関数内のencoded_image=generate_graph(dates, protein, energy, fat, cholesterol, carbohydrates)に修正しました。

user_id=user_idだと変数名と同じ名前のキーワード引数を関数やメソッドに渡してしまうことが原因だと思い
変数とキーワード引数の名前を区別するため{'user_id': user_id} の辞書を使用しました。

get_nutrients_data_today、compute_nutrients、group_entries_by_date関数でentries 内で user_id のフィルタリングがされていないことが原因で異なるユーザーに同じ栄養素のデータを表示させていたと思います。
なのでentries 内で user_id 属性が存在し、その値が指定された user_id と一致する要素を抽出し、それらの要素からなる新しいリスト user_entries を作成するように変更しました。

よろしくお願いいたします。

2023-09-25 02:44 UTC, ayabe2000 commented
foodの削除した部分を追加しもとに戻しました。

2023-09-25 05:24 UTC, masatanish requested changes

2023-09-25 05:24 UTC, masatanish commented on views.py
> +    user_entries = [entry for entry in entries if hasattr(entry, 'user_id') and entry.user_id == user_id]
`dashboard()` で `all_entries` を取得し、 この関数内でuser_idで絞っていますが、 `dashboard()` の中で`FoodEntry` をユーザIDに絞った取得をすれば、 この関数に `user_id` を渡す必要はないと考えます。

なお、`FoodEntry` でユーザを絞った情報取得をする際には、 クエリにユーザIDの条件を設定して絞り込みをしてください。
(上記のようにfor文での絞り込みはデータが大量になった場合に効率的ではないのでやめましょう)

2023-09-25 05:24 UTC, masatanish commented on views.py
> +    user_entries = [entry for entry in all_entries if entry.user_id == user_id]
`compute_nutrients` と同様にここにuser_idとall_entiresを渡す必要はないと考えます。

2023-09-26 02:10 UTC, ayabe2000 commented
views.pyのファイルを修正前に戻しました。
（ユーザー識別に関する修正した部分をissue作成前に戻しました）

ご確認よろしくお願いいたします。

2023-09-26 02:16 UTC, masatanish commented
> FoodEntry をユーザIDに絞った取得をすれば、 この関数に user_id を渡す必要はないと考えます。

とコメントしました。 もとに戻しただけでは「 FoodEntry をユーザIDに絞った取得をすれば、 」の部分が対応できていないと思います。
(なので本来対応したかった問題に対応できていないのではと思います)

```python
    all_entries = FoodEntry.query.order_by(FoodEntry.date.desc()).all()
```
ここですべてのエントリを取得するのではなく、ユーザを絞った取得をすれば良いのではないかという提案でした。
具体的には`filter()`を使ってユーザの絞り込みを行ってください。

2023-09-27 02:51 UTC, ayabe2000 commented
ご指摘いただきありがとうございます。
filter()を利用して特定のユーザーに関連するエントリのみ取得するようにしました。
 all_entries = FoodEntry.query.filter(FoodEntry.user_id == user_id).all()

ご確認よろしくお願いいたします。

2023-09-28 00:36 UTC, masatanish requested changes

2023-09-28 00:36 UTC, masatanish commented on views.py
> +    all_entries = FoodEntry.query.filter(FoodEntry.user_id == user_id).all()
`all_entries` という変数名は、実態と乖離しているので修正してください。
他の人がソースを見るときに混乱します。

2023-09-28 01:54 UTC, ayabe2000 commented
views.pyのdashboard関数の
all_entries をselected_food_nutrientに変数名を変更しました。

ご確認お願いいたします。

2023-09-28 08:19 UTC, masatanish commented
良いと思います。Mergeしてください。

2023-09-28 08:44 UTC, merged